CREATE TABLE `wp_icl_languages` (  `id` int(11) NOT NULL AUTO_INCREMENT,  `code` varchar(7) NOT NULL,  `english_name` varchar(128) NOT NULL,  `major` tinyint(4) NOT NULL DEFAULT '0',  `active` tinyint(4) NOT NULL,  `default_locale` varchar(8) DEFAULT NULL,  `tag` varchar(8) DEFAULT NULL,  `encode_url` tinyint(1) NOT NULL DEFAULT '0',  PRIMARY KEY (`id`),  UNIQUE KEY `code` (`code`),  UNIQUE KEY `english_name` (`english_name`)) ENGINE=MyISAM AUTO_INCREMENT=65 DEFAULT CHARSET=utf8;
/*!40000 ALTER TABLE `wp_icl_languages` DISABLE KEYS */;
INSERT INTO `wp_icl_languages` VALUES('1', 'en', 'English', '1', '1', 'en_US', 'en-US', '0');
INSERT INTO `wp_icl_languages` VALUES('2', 'es', 'Spanish', '1', '1', 'es_ES', 'es-ES', '0');
INSERT INTO `wp_icl_languages` VALUES('3', 'de', 'German', '1', '0', 'de_DE', 'de-DE', '0');
INSERT INTO `wp_icl_languages` VALUES('4', 'fr', 'French', '1', '0', 'fr_FR', 'fr-FR', '0');
INSERT INTO `wp_icl_languages` VALUES('5', 'ar', 'Arabic', '0', '0', 'ar', 'ar', '0');
INSERT INTO `wp_icl_languages` VALUES('6', 'bs', 'Bosnian', '0', '0', '', '', '0');
INSERT INTO `wp_icl_languages` VALUES('7', 'bg', 'Bulgarian', '0', '0', 'bg_BG', 'bg-BG', '0');
INSERT INTO `wp_icl_languages` VALUES('8', 'ca', 'Catalan', '0', '0', 'ca', 'ca', '0');
INSERT INTO `wp_icl_languages` VALUES('9', 'cs', 'Czech', '0', '0', 'cs_CZ', 'cs-CZ', '0');
INSERT INTO `wp_icl_languages` VALUES('10', 'sk', 'Slovak', '0', '0', 'sk_SK', 'sk-SK', '0');
INSERT INTO `wp_icl_languages` VALUES('11', 'cy', 'Welsh', '0', '0', 'cy', 'cy', '0');
INSERT INTO `wp_icl_languages` VALUES('12', 'da', 'Danish', '1', '0', 'da_DK', 'da-DK', '0');
INSERT INTO `wp_icl_languages` VALUES('13', 'el', 'Greek', '0', '0', 'el', 'el', '0');
INSERT INTO `wp_icl_languages` VALUES('14', 'eo', 'Esperanto', '0', '0', 'eo', 'eo', '0');
INSERT INTO `wp_icl_languages` VALUES('15', 'et', 'Estonian', '0', '0', 'et', 'et', '0');
INSERT INTO `wp_icl_languages` VALUES('16', 'eu', 'Basque', '0', '0', 'eu', 'eu', '0');
INSERT INTO `wp_icl_languages` VALUES('17', 'fa', 'Persian', '0', '0', 'fa_IR', 'fa-IR', '0');
INSERT INTO `wp_icl_languages` VALUES('18', 'fi', 'Finnish', '0', '0', 'fi', 'fi', '0');
INSERT INTO `wp_icl_languages` VALUES('19', 'ga', 'Irish', '0', '0', '', '', '0');
INSERT INTO `wp_icl_languages` VALUES('20', 'he', 'Hebrew', '0', '0', 'he_IL', 'he-IL', '0');
INSERT INTO `wp_icl_languages` VALUES('21', 'hi', 'Hindi', '0', '0', '', '', '0');
INSERT INTO `wp_icl_languages` VALUES('22', 'hr', 'Croatian', '0', '0', 'hr', 'hr', '0');
INSERT INTO `wp_icl_languages` VALUES('23', 'hu', 'Hungarian', '0', '0', 'hu_HU', 'hu-HU', '0');
INSERT INTO `wp_icl_languages` VALUES('24', 'hy', 'Armenian', '0', '0', '', '', '0');
INSERT INTO `wp_icl_languages` VALUES('25', 'id', 'Indonesian', '0', '0', 'id_ID', 'id-ID', '0');
INSERT INTO `wp_icl_languages` VALUES('26', 'is', 'Icelandic', '0', '0', 'is_IS', 'is-IS', '0');
INSERT INTO `wp_icl_languages` VALUES('27', 'it', 'Italian', '1', '0', 'it_IT', 'it-IT', '0');
INSERT INTO `wp_icl_languages` VALUES('28', 'ja', 'Japanese', '1', '0', 'ja', 'ja', '0');
INSERT INTO `wp_icl_languages` VALUES('29', 'ko', 'Korean', '0', '0', 'ko_KR', 'ko-KR', '0');
INSERT INTO `wp_icl_languages` VALUES('30', 'ku', 'Kurdish', '0', '0', 'ku', 'ku', '0');
INSERT INTO `wp_icl_languages` VALUES('31', 'la', 'Latin', '0', '0', '', '', '0');
INSERT INTO `wp_icl_languages` VALUES('32', 'lv', 'Latvian', '0', '0', 'lv', 'lv', '0');
INSERT INTO `wp_icl_languages` VALUES('33', 'lt', 'Lithuanian', '0', '0', 'lt', 'lt', '0');
INSERT INTO `wp_icl_languages` VALUES('34', 'mk', 'Macedonian', '0', '0', 'mk_MK', 'mk-MK', '0');
INSERT INTO `wp_icl_languages` VALUES('35', 'mt', 'Maltese', '0', '0', '', '', '0');
INSERT INTO `wp_icl_languages` VALUES('36', 'mo', 'Moldavian', '0', '0', '', '', '0');
INSERT INTO `wp_icl_languages` VALUES('37', 'mn', 'Mongolian', '0', '0', '', '', '0');
INSERT INTO `wp_icl_languages` VALUES('38', 'ne', 'Nepali', '0', '0', '', '', '0');
INSERT INTO `wp_icl_languages` VALUES('39', 'nl', 'Dutch', '1', '0', 'nl_NL', 'nl-NL', '0');
INSERT INTO `wp_icl_languages` VALUES('40', 'nb', 'Norwegian Bokmål', '0', '0', 'nb_NO', 'nb-NO', '0');
INSERT INTO `wp_icl_languages` VALUES('41', 'pa', 'Punjabi', '0', '0', '', '', '0');
INSERT INTO `wp_icl_languages` VALUES('42', 'pl', 'Polish', '0', '0', 'pl_PL', 'pl-PL', '0');
INSERT INTO `wp_icl_languages` VALUES('43', 'pt-pt', 'Portuguese, Portugal', '0', '0', 'pt_PT', 'pt-PT', '0');
INSERT INTO `wp_icl_languages` VALUES('44', 'pt-br', 'Portuguese, Brazil', '0', '0', 'pt_BR', 'pt-BR', '0');
INSERT INTO `wp_icl_languages` VALUES('45', 'qu', 'Quechua', '0', '0', '', '', '0');
INSERT INTO `wp_icl_languages` VALUES('46', 'ro', 'Romanian', '0', '0', 'ro_RO', 'ro-RO', '0');
INSERT INTO `wp_icl_languages` VALUES('47', 'ru', 'Russian', '1', '0', 'ru_RU', 'ru-RU', '0');
INSERT INTO `wp_icl_languages` VALUES('48', 'sl', 'Slovenian', '0', '0', 'sl_SI', 'sl-SI', '0');
INSERT INTO `wp_icl_languages` VALUES('49', 'so', 'Somali', '0', '0', '', '', '0');
INSERT INTO `wp_icl_languages` VALUES('50', 'sq', 'Albanian', '0', '0', '', '', '0');
INSERT INTO `wp_icl_languages` VALUES('51', 'sr', 'Serbian', '0', '0', 'sr_RS', 'sr-RS', '0');
INSERT INTO `wp_icl_languages` VALUES('52', 'sv', 'Swedish', '0', '0', 'sv_SE', 'sv-SE', '0');
INSERT INTO `wp_icl_languages` VALUES('53', 'ta', 'Tamil', '0', '0', '', '', '0');
INSERT INTO `wp_icl_languages` VALUES('54', 'th', 'Thai', '0', '0', 'th', 'th', '0');
INSERT INTO `wp_icl_languages` VALUES('55', 'tr', 'Turkish', '0', '0', 'tr', 'tr', '0');
INSERT INTO `wp_icl_languages` VALUES('56', 'uk', 'Ukrainian', '0', '0', 'uk_UA', 'uk-UA', '0');
INSERT INTO `wp_icl_languages` VALUES('57', 'ur', 'Urdu', '0', '0', '', '', '0');
INSERT INTO `wp_icl_languages` VALUES('58', 'uz', 'Uzbek', '0', '0', 'uz_UZ', 'uz-UZ', '0');
INSERT INTO `wp_icl_languages` VALUES('59', 'vi', 'Vietnamese', '0', '0', 'vi', 'vi', '0');
INSERT INTO `wp_icl_languages` VALUES('60', 'yi', 'Yiddish', '0', '0', '', '', '0');
INSERT INTO `wp_icl_languages` VALUES('61', 'zh-hans', 'Chinese (Simplified)', '1', '0', 'zh_CN', 'zh-CN', '0');
INSERT INTO `wp_icl_languages` VALUES('62', 'zu', 'Zulu', '0', '0', '', '', '0');
INSERT INTO `wp_icl_languages` VALUES('63', 'zh-hant', 'Chinese (Traditional)', '1', '0', 'zh_TW', 'zh-TW', '0');
INSERT INTO `wp_icl_languages` VALUES('64', 'ms', 'Malay', '0', '0', 'ms_MY', 'ms-MY', '0');
/*!40000 ALTER TABLE `wp_icl_languages` ENABLE KEYS */;
