CREATE TABLE `wp_terms` (  `term_id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,  `name` varchar(200) NOT NULL DEFAULT '',  `slug` varchar(200) NOT NULL DEFAULT '',  `term_group` bigint(10) NOT NULL DEFAULT '0',  PRIMARY KEY (`term_id`),  UNIQUE KEY `slug` (`slug`),  KEY `name` (`name`)) ENGINE=MyISAM AUTO_INCREMENT=110 DEFAULT CHARSET=utf8;
/*!40000 ALTER TABLE `wp_terms` DISABLE KEYS */;
INSERT INTO `wp_terms` VALUES('1', 'Uncategorized', 'uncategorized', '0');
INSERT INTO `wp_terms` VALUES('2', 'Caminata al volcan', 'caminata-al-volcan', '0');
INSERT INTO `wp_terms` VALUES('3', 'Canopy', 'canopy', '0');
INSERT INTO `wp_terms` VALUES('4', 'Design', 'design', '0');
INSERT INTO `wp_terms` VALUES('5', 'Music', 'music', '0');
INSERT INTO `wp_terms` VALUES('6', 'Photography', 'photography', '0');
INSERT INTO `wp_terms` VALUES('7', 'Sport', 'sport', '0');
INSERT INTO `wp_terms` VALUES('8', 'Analysis', 'analysis', '0');
INSERT INTO `wp_terms` VALUES('9', 'Articles', 'articles', '0');
INSERT INTO `wp_terms` VALUES('10', 'Audio', 'audio', '0');
INSERT INTO `wp_terms` VALUES('11', 'Culture', 'culture', '0');
INSERT INTO `wp_terms` VALUES('12', 'Development', 'development', '0');
INSERT INTO `wp_terms` VALUES('13', 'Ecology', 'ecology', '0');
INSERT INTO `wp_terms` VALUES('14', 'Events', 'events', '0');
INSERT INTO `wp_terms` VALUES('15', 'Information', 'information', '0');
INSERT INTO `wp_terms` VALUES('16', 'Inspiration', 'inspiration', '0');
INSERT INTO `wp_terms` VALUES('17', 'Nature', 'nature', '0');
INSERT INTO `wp_terms` VALUES('18', 'Opportunities', 'opportunities', '0');
INSERT INTO `wp_terms` VALUES('19', 'Science', 'science', '0');
INSERT INTO `wp_terms` VALUES('20', 'Stress', 'stress', '0');
INSERT INTO `wp_terms` VALUES('21', 'Swimming', 'swimming', '0');
INSERT INTO `wp_terms` VALUES('22', 'Trends', 'trends', '0');
INSERT INTO `wp_terms` VALUES('23', 'Video', 'video', '0');
INSERT INTO `wp_terms` VALUES('24', 'Web Design', 'web-design', '0');
INSERT INTO `wp_terms` VALUES('25', 'art', 'art-2', '0');
INSERT INTO `wp_terms` VALUES('26', 'Clients Carousel Dark', 'clients-carousel-dark', '0');
INSERT INTO `wp_terms` VALUES('27', 'Clients Carousel Light', 'clients-carousel-light', '0');
INSERT INTO `wp_terms` VALUES('28', 'Clients Carousel Light', 'clients-carousel-light-2', '0');
INSERT INTO `wp_terms` VALUES('29', 'Rafting', 'rafting', '0');
INSERT INTO `wp_terms` VALUES('30', 'Rappel', 'rappel', '0');
INSERT INTO `wp_terms` VALUES('31', 'Home Business Slider', 'home-business-slider', '0');
INSERT INTO `wp_terms` VALUES('33', 'Home Shop Slider', 'home-shop-slider', '0');
INSERT INTO `wp_terms` VALUES('34', 'Home Shop Slider', 'home-shop-slider-2', '0');
INSERT INTO `wp_terms` VALUES('35', 'Home Slider', 'home-slider', '0');
INSERT INTO `wp_terms` VALUES('36', 'leadership', 'leadership', '0');
INSERT INTO `wp_terms` VALUES('38', 'web design', 'web-design-2', '0');
INSERT INTO `wp_terms` VALUES('39', 'web design', 'web-design-2-2', '0');
INSERT INTO `wp_terms` VALUES('40', 'web development', 'web-development', '0');
INSERT INTO `wp_terms` VALUES('41', 'footer_menu', 'footer_menu', '0');
INSERT INTO `wp_terms` VALUES('42', 'footer_menu', 'footer_menu-2', '0');
INSERT INTO `wp_terms` VALUES('43', 'top_menu', 'top_menu', '0');
INSERT INTO `wp_terms` VALUES('44', 'side_menu', 'side_menu', '0');
INSERT INTO `wp_terms` VALUES('45', 'side_menu', 'side_menu-2', '0');
INSERT INTO `wp_terms` VALUES('46', 'Gallery', 'post-format-gallery', '0');
INSERT INTO `wp_terms` VALUES('47', 'Audio', 'post-format-audio', '0');
INSERT INTO `wp_terms` VALUES('48', 'Link', 'post-format-link', '0');
INSERT INTO `wp_terms` VALUES('49', 'Link', 'post-format-link-2', '0');
INSERT INTO `wp_terms` VALUES('50', 'Quote', 'post-format-quote', '0');
INSERT INTO `wp_terms` VALUES('51', 'Video', 'post-format-video', '0');
INSERT INTO `wp_terms` VALUES('52', 'simple', 'simple', '0');
INSERT INTO `wp_terms` VALUES('53', 'grouped', 'grouped', '0');
INSERT INTO `wp_terms` VALUES('54', 'variable', 'variable', '0');
INSERT INTO `wp_terms` VALUES('55', 'external', 'external', '0');
INSERT INTO `wp_terms` VALUES('56', 'Rio Celeste', 'rio-celeste', '0');
INSERT INTO `wp_terms` VALUES('57', 'Sunset Lake', 'sunset-lake', '0');
INSERT INTO `wp_terms` VALUES('58', 'Hoteles', 'hoteles', '0');
INSERT INTO `wp_terms` VALUES('59', 'Transportes', 'transportes', '0');
INSERT INTO `wp_terms` VALUES('60', 'Puentes Colgantes', 'puentes-colgantes', '0');
INSERT INTO `wp_terms` VALUES('61', 'TOURS', 'tours', '0');
INSERT INTO `wp_terms` VALUES('62', 'NATURE TOURS', 'nature-tours', '0');
INSERT INTO `wp_terms` VALUES('63', 'ADVENTURE TOURS', 'adventure-tours', '0');
INSERT INTO `wp_terms` VALUES('64', 'Paquetes de Luna de miel.', 'paquetes-de-luna-de-miel', '0');
INSERT INTO `wp_terms` VALUES('65', 'Cavernas Venado', 'cavernas-venado', '0');
INSERT INTO `wp_terms` VALUES('66', 'Caño negro', 'cano-negro', '0');
INSERT INTO `wp_terms` VALUES('67', 'Uncategorized @en', 'uncategorized-en', '0');
INSERT INTO `wp_terms` VALUES('68', 'Volcano Hike', 'volcano-hike', '0');
INSERT INTO `wp_terms` VALUES('69', 'Canopy', 'canopy-en', '0');
INSERT INTO `wp_terms` VALUES('70', 'Cavernas Venado', 'cavernas-venado-en', '0');
INSERT INTO `wp_terms` VALUES('71', 'Caño Negro', 'cano-negro-en', '0');
INSERT INTO `wp_terms` VALUES('72', 'Puentes Colgantes', 'puentes-colgantes-en', '0');
INSERT INTO `wp_terms` VALUES('73', 'Rafting', 'rafting-en', '0');
INSERT INTO `wp_terms` VALUES('74', 'Rappel', 'rappel-en', '0');
INSERT INTO `wp_terms` VALUES('75', 'Rio Celeste', 'rio-celeste-en', '0');
INSERT INTO `wp_terms` VALUES('76', 'Monteverde', 'monteverde', '0');
INSERT INTO `wp_terms` VALUES('77', 'Aeropuerto', 'aeropuerto', '0');
INSERT INTO `wp_terms` VALUES('78', 'Arenal', 'arenal', '0');
INSERT INTO `wp_terms` VALUES('79', 'Guanacaste', 'guanacaste', '0');
INSERT INTO `wp_terms` VALUES('80', 'Jaco', 'jaco', '0');
INSERT INTO `wp_terms` VALUES('81', 'Limon', 'limon', '0');
INSERT INTO `wp_terms` VALUES('82', 'San Jose', 'san-jose', '0');
INSERT INTO `wp_terms` VALUES('83', 'Manuel Antonio', 'manuel-antonio', '0');
INSERT INTO `wp_terms` VALUES('84', 'booking', 'booking', '0');
INSERT INTO `wp_terms` VALUES('85', 'footer_menu - Inglés0', 'footer_menu-ingles0', '0');
INSERT INTO `wp_terms` VALUES('86', 'footer_menu - Inglés-2', 'footer_menu-ingles-2', '0');
INSERT INTO `wp_terms` VALUES('87', 'top_menu - Inglés0', 'top_menu-ingles0', '0');
INSERT INTO `wp_terms` VALUES('88', 'side_menu - Inglés0', 'side_menu-ingles0', '0');
INSERT INTO `wp_terms` VALUES('89', 'side_menu - Inglés-2', 'side_menu-ingles-2', '0');
INSERT INTO `wp_terms` VALUES('90', 'art', 'art-2-en', '0');
INSERT INTO `wp_terms` VALUES('91', 'simple', 'simple-en', '0');
INSERT INTO `wp_terms` VALUES('92', 'Transportation', 'transportation-en', '0');
INSERT INTO `wp_terms` VALUES('93', 'San Jose', 'san-jose-en', '0');
INSERT INTO `wp_terms` VALUES('94', 'Monteverde', 'monteverde-en', '0');
INSERT INTO `wp_terms` VALUES('95', 'Adventure Package', 'adventure-package-en', '0');
INSERT INTO `wp_terms` VALUES('98', 'Airport hotels', 'airport-hotels-en', '0');
INSERT INTO `wp_terms` VALUES('97', 'Hotels', 'hotels-en', '0');
INSERT INTO `wp_terms` VALUES('99', 'Guanacaste', 'guanacaste-en', '0');
INSERT INTO `wp_terms` VALUES('100', 'Jaco', 'jaco-en', '0');
INSERT INTO `wp_terms` VALUES('101', 'Limon', 'limon-en', '0');
INSERT INTO `wp_terms` VALUES('102', 'Manuel Antonio', 'manuelantonio-en', '0');
INSERT INTO `wp_terms` VALUES('103', 'Honey moon packages', 'honey-moon-packages-en', '0');
INSERT INTO `wp_terms` VALUES('104', 'Nature package', 'nature-package-en', '0');
INSERT INTO `wp_terms` VALUES('105', 'Arenal', 'arenal-en', '0');
INSERT INTO `wp_terms` VALUES('106', 'Tours', 'tours-en', '0');
INSERT INTO `wp_terms` VALUES('107', 'Home Shop Slider', 'home-shop-slider-3', '0');
INSERT INTO `wp_terms` VALUES('108', 'hiking', 'hiking', '0');
INSERT INTO `wp_terms` VALUES('109', 'Monteverde', 'monteverde-es', '0');
/*!40000 ALTER TABLE `wp_terms` ENABLE KEYS */;
